export const VENEZUELA_ESTADOS = [
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Distrito Capital',
  'Falcón',
  'Guárico',
  'Lara',
  'La Guaira',
  'Mérida',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'Vargas',
  'Yaracuy',
  'Zulia',
] as const

export type VenezuelaEstado = (typeof VENEZUELA_ESTADOS)[number]

/** Most affected by the 2026 earthquake — quick filters on /buscar */
export const PRIORITY_ESTADOS = [
  'La Guaira',
  'Distrito Capital',
  'Miranda',
  'Carabobo',
  'Aragua',
  'Yaracuy',
] as const

export type GeoData = {
  municipios: Record<string, string[]>
  parroquias: Record<string, string[]>
}

/** Municipios per estado; parroquias for priority regions only */
export const VENEZUELA_GEO: GeoData = {
  municipios: {
    'La Guaira': [
      'Vargas',
      'Caraballeda',
      'Catia La Mar',
      'La Guaira',
      'Macuto',
      'Maiquetía',
      'Naiguatá',
      'Carayaca',
    ],
    'Distrito Capital': [
      'Libertador',
      'Sucre',
      'Baruta',
      'Chacao',
      'El Hatillo',
    ],
    Miranda: [
      'Acevedo',
      'Andrés Bello',
      'Baruta',
      'Brión',
      'Buroz',
      'Carrizal',
      'Chacao',
      'Cristóbal Rojas',
      'El Hatillo',
      'Guaicaipuro',
      'Independencia',
      'Lander',
      'Los Salias',
      'Páez',
      'Paz Castillo',
      'Pedro Gual',
      'Plaza',
      'Simón Bolívar',
      'Sucre',
      'Urdaneta',
      'Zamora',
    ],
    Carabobo: [
      'Bejuma',
      'Carlos Arvelo',
      'Diego Ibarra',
      'Guacara',
      'Juan José Mora',
      'Libertador',
      'Los Guayos',
      'Miranda',
      'Montalbán',
      'Naguanagua',
      'Puerto Cabello',
      'San Diego',
      'San Joaquín',
      'Valencia',
    ],
    Aragua: [
      'Bolívar',
      'Camatagua',
      'Francisco Linares Alcántara',
      'Girardot',
      'José Ángel Lamas',
      'José Félix Ribas',
      'José Rafael Revenga',
      'Libertador',
      'Mario Briceño Iragorry',
      'Ocumare de la Costa de Oro',
      'San Casimiro',
      'San Sebastián',
      'Santiago Mariño',
      'Santos Michelena',
      'Sucre',
      'Tovar',
      'Urdaneta',
      'Zamora',
    ],
    Yaracuy: [
      'Arístides Bastidas',
      'Bolívar',
      'Bruzual',
      'Cocorote',
      'Independencia',
      'José Antonio Páez',
      'La Trinidad',
      'Manuel Monge',
      'Nirgua',
      'Peña',
      'San Felipe',
      'Sucre',
      'Urachiche',
      'Veroes',
    ],
    Zulia: ['Maracaibo', 'San Francisco', 'Cabimas', 'Lagunillas', 'Mara', 'Colón'],
    Lara: ['Iribarren', 'Palavecino', 'Torres', 'Jiménez', 'Morán'],
    Bolívar: ['Caroní', 'Heres', 'Piar', 'Angostura', 'Sifontes'],
    'Nueva Esparta': ['García', 'Gómez', 'Maneiro', 'Marcano', 'Antolín del Campo'],
    Táchira: ['San Cristóbal', 'Cárdenas', 'Uribante', 'Junín', 'Lobatera'],
    Mérida: ['Libertador', 'Campo Elías', 'Sucre', 'Rangel', 'Tovar'],
    Sucre: ['Sucre', 'Benítez', 'Bermúdez', 'Cruz Salmerón Acosta', 'Ribero'],
    Anzoátegui: ['Simón Bolívar', 'Sotillo', 'Anaco', 'Freites', 'Guanta'],
    Falcón: ['Miranda', 'Carirubana', 'Colina', 'Dabajuro', 'Silva'],
    Guárico: ['Roscio', 'Infante', 'Zaraza', 'Monagas', 'Camaguán'],
    Portuguesa: ['Araure', 'Guanare', 'Guanarito', 'Ospino', 'Páez'],
    Barinas: ['Barinas', 'Bolívar', 'Pedraza', 'Sosa', 'Obispos'],
    Apure: ['Achaguas', 'Biruaca', 'Muñoz', 'Páez', 'San Fernando'],
    Amazonas: ['Atures', 'Autana', 'Manapiare', 'Maroa', 'Río Negro'],
    Cojedes: ['Girardot', 'Lima Blanco', 'Pao de San Juan Bautista', 'Ricaurte', 'Tinaco'],
    'Delta Amacuro': ['Antonio Díaz', 'Casacoima', 'Pedernales', 'Tucupita'],
    Monagas: ['Maturín', 'Caripe', 'Piar', 'Punceres', 'Sotillo'],
    Trujillo: ['Trujillo', 'Boconó', 'Carache', 'Escuque', 'Valera'],
    Vargas: ['Vargas'],
  },
  parroquias: {
    'La Guaira|Vargas': ['Caraballeda', 'Carayaca', 'Catia La Mar', 'La Guaira', 'Macuto', 'Maiquetía', 'Naiguatá'],
    'La Guaira|Caraballeda': ['Caraballeda'],
    'La Guaira|Catia La Mar': ['Catia La Mar'],
    'La Guaira|La Guaira': ['La Guaira'],
    'La Guaira|Maiquetía': ['Maiquetía'],
    'Distrito Capital|Libertador': [
      'Altagracia',
      'Antímano',
      'Candelaria',
      'Caricuao',
      'Catedral',
      'Coche',
      'El Junquito',
      'El Paraíso',
      'El Recreo',
      'El Valle',
      'La Pastora',
      'La Vega',
      'Macarao',
      'San Agustín',
      'San Bernardino',
      'San José',
      'San Juan',
      'San Pedro',
      'Santa Rosalía',
      'Santa Teresa',
      'Sucre',
      '23 de Enero',
    ],
    'Distrito Capital|Sucre': ['Petare', 'Caucagüita', 'Filas de Mariche', 'La Dolorita', 'Leoncio Martínez'],
    'Distrito Capital|Baruta': ['Baruta', 'El Cafetal', 'Las Minas de Baruta'],
    'Distrito Capital|Chacao': ['Chacao'],
    'Distrito Capital|El Hatillo': ['El Hatillo'],
    'Miranda|Chacao': ['Chacao'],
    'Miranda|Baruta': ['Baruta', 'El Cafetal', 'Las Minas de Baruta'],
    'Miranda|El Hatillo': ['El Hatillo'],
    'Miranda|Sucre': ['Petare', 'Caucagüita', 'Filas de Mariche', 'La Dolorita', 'Leoncio Martínez'],
    'Miranda|Plaza': ['Guarenas'],
    'Miranda|Zamora': ['Guatire'],
    'Carabobo|Valencia': ['Candelaria', 'Catedral', 'El Socorro', 'Miguel Peña', 'Negro Primero', 'Rafael Urdaneta', 'San Blas', 'San José', 'Santa Rosa'],
    'Carabobo|Puerto Cabello': ['Bartolomé Salóm', 'Democracia', 'Fraternidad', 'Goaigoaza', 'Juan José Flores', 'Patanemo', 'San Esteban'],
    'Carabobo|Naguanagua': ['Naguanagua'],
    'Aragua|Girardot': ['Choroní', 'Las Delicias', 'Los Tacariguas', 'Maracay', 'Pedro José Ovalles'],
    'Aragua|Libertador': ['Palo Negro', 'San Martín de Porres'],
    'Yaracuy|San Felipe': ['Albarico', 'San Felipe', 'San Javier'],
    'Yaracuy|Independencia': ['Independencia'],
  },
}

export function getMunicipiosForEstado(estado: string): string[] {
  return VENEZUELA_GEO.municipios[estado] ?? []
}

export function getParroquiasForMunicipio(estado: string, municipio: string): string[] {
  return VENEZUELA_GEO.parroquias[`${estado}|${municipio}`] ?? []
}

/** Map "Caracas" filter label to DB estado value */
export function normalizeEstadoFilter(filter: string): string {
  if (filter === 'Caracas') return 'Distrito Capital'
  return filter
}
